version: '3.8'

services:
  # Servicio Web (Mi p√°gina web)
  app:
    build: .
    container_name: mvc_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html # Sincroniza la carpeta local con el contenedor
    depends_on:
      - db
  # Servicio de Base de Datos
  db:
    image: mysql:8.0
    container_name: mvc_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvc_project # Nombre de la base de datos, TODO: cambiar por nombre de la Empresa
      MYSQL_USER: user # TODO: cambiar por admin?
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  # Agregamos esto para gestionar la BD visualmente TODO: es necesario? Pq igual estamso usando MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mvc_pma
    links:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"

## levantar el entorno con: docker-compose up -d --build